### ISSUE TITLE
License is (probably) not a "special license"

### ISSUE THREAD

**Issue by cameronbosch** [flathub/io.github.efogdev.mpris-timer#4]
This program says it is licensed under the MIT license. It should say this, however, the Flathub listing says:

"This app is developed under the special license MIT +no-false-attribs license.
You may or may not be able to contribute to this app."

It says that the program is licences under a special license when as far as I can tell, it's just the MIT license. Could somebody clear up what is going on and/or fix the actual license on Flathub? (Is it the MIT license or not?)

![image of the Flathub listing](https://github.com/user-attachments/assets/92ac9ee6-c376-4807-aa87-e21a384c3879)

**Comment by efogdev** [comment]
I'm curious too. The license is MITNFA, not MIT: https://spdx.org/licenses/MITNFA.html — but yeah, in fact it IS just MIT with a little correction, and is probably unknown to Flathub. I've already started a topic on Flathub forum: 
https://discourse.flathub.org/t/why-does-my-app-have-proprietary-code-badge/8062

**Comment by efogdev** [comment]
I've decided to change the license to MIT
